/**
 * appBuilder — minimal app-project generator used by ChatbotPage's
 * "build an app" intent flow. Generates a self-contained static
 * HTML/CSS/JS project from a natural-language prompt and hands it
 * to the Code IDE via openProjectInIde().
 */

export type AppBuilderPlatform = "web" | "mobile";

export interface GenerateAppProjectOptions {
  prompt: string;
  platform?: AppBuilderPlatform | string;
  accessToken?: string | null;
  personality?: string;
  mode?: string;
  providerPayload?: Record<string, unknown>;
}

export interface GeneratedAppFile {
  name: string;
  language?: string;
  content: string;
}

export interface GeneratedAppProject {
  title: string;
  platform: AppBuilderPlatform;
  description: string;
  files: GeneratedAppFile[];
}

const APP_INTENT_RE =
  /\b(build|make|create|generate|scaffold)\b[^.?!]{0,40}\b(app|application|site|website|web app|dashboard|landing page|tool|game)\b/i;

/** Lightweight intent detection: does this message ask for an app/site? */
export function detectAppBuilderIntent(message: string): boolean {
  if (!message || message.length > 600) return false;
  return APP_INTENT_RE.test(message);
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function titleFromPrompt(prompt: string): string {
  const cleaned = prompt.trim().replace(/\s+/g, " ").slice(0, 48);
  const titled = cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
  return titled.length > 0 ? titled : "My App";
}

/**
 * Generate a minimal but runnable static app project.
 * The result is opened in the Code IDE where the user can preview it live.
 */
export async function generateAppProject(
  opts: GenerateAppProjectOptions,
): Promise<GeneratedAppProject> {
  const platform: AppBuilderPlatform =
    opts.platform === "mobile" ? "mobile" : "web";
  const title = titleFromPrompt(opts.prompt || "My App");
  const safePrompt = escapeHtml((opts.prompt || "").slice(0, 400));

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <main class="shell">
    <header>
      <h1>${escapeHtml(title)}</h1>
      <p class="tagline">Generated by ShadowTalk AI App Builder</p>
    </header>
    <section class="card">
      <h2>Request</h2>
      <p>${safePrompt}</p>
    </section>
    <section class="card">
      <h2>Next steps</h2>
      <p>Ask ShadowTalk to add features, screens, or connect a backend — this project is fully editable in the Code IDE.</p>
      <button id="action-btn">Get started</button>
      <p id="output" role="status"></p>
    </section>
  </main>
  <script src="app.js"></script>
</body>
</html>
`;

  const css = `:root {
  --bg: #0b1020;
  --card: #151b31;
  --text: #e6e9f2;
  --muted: #9aa3b8;
  --accent: #4f8cff;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
  background: var(--bg);
  color: var(--text);
  min-height: 100vh;
  display: grid;
  place-items: center;
  padding: 24px;
}
.shell { width: 100%; max-width: 720px; }
header { margin-bottom: 24px; }
h1 { font-size: 1.9rem; letter-spacing: -0.02em; }
.tagline { color: var(--muted); margin-top: 6px; font-size: 0.95rem; }
.card {
  background: var(--card);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 14px;
  padding: 20px;
  margin-bottom: 16px;
}
.card h2 { font-size: 1.05rem; margin-bottom: 10px; color: var(--accent); }
.card p { line-height: 1.6; color: var(--text); }
button {
  margin-top: 14px;
  background: var(--accent);
  color: #fff;
  border: none;
  border-radius: 8px;
  padding: 10px 18px;
  font-size: 0.95rem;
  cursor: pointer;
}
button:hover { filter: brightness(1.1); }
#output { margin-top: 10px; color: var(--muted); font-size: 0.9rem; }
`;

  const js = `document.addEventListener("DOMContentLoaded", () => {
  const btn = document.getElementById("action-btn");
  const out = document.getElementById("output");
  let clicks = 0;
  if (btn && out) {
    btn.addEventListener("click", () => {
      clicks += 1;
      out.textContent = \`Nice! The app skeleton works (\${clicks} click\${clicks === 1 ? "" : "s"}).\`;
    });
  }
});
`;

  return {
    title,
    platform,
    description: `A ${platform} app scaffold generated from your request: "${(opts.prompt || "").slice(0, 120)}".`,
    files: [
      { name: "index.html", language: "html", content: html },
      { name: "styles.css", language: "css", content: css },
      { name: "app.js", language: "javascript", content: js },
    ],
  };
}
